name       : libdazzle
version    : 3.32.1
release    : 4
source     :
    - https://download.gnome.org/sources/libdazzle/3.32/libdazzle-3.32.1.tar.xz : 238da19fdcc3ae9bb0c2d781d099fb8c6ec70c4dd3dffad80d230344ecc3f972
license    : GPL-3.0-or-later
component  : programming.library
summary    : The libdazzle library is a companion library to GObject and Gtk+. It provides various features that we wish were in the underlying library but cannot for various reasons.
description: |
    The libdazzle library is a companion library to GObject and Gtk+. It provides various features that we wish were in the underlying library but cannot for various reasons.
builddeps  :
    - pkgconfig(gio-2.0)
    - pkgconfig(gtk+-3.0)
    - gtk-doc
    - valadoc
setup      : |
    %meson_configure \
        -Denable_gtk_doc=true \
        -Denable_tools=true
build      : |
    %ninja_build
install    : |
    %ninja_install
